# Generated by Django 5.1.7 on 2025-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('advertiser_id', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('abbrevation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('face_centered_photo', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
