# Generated by Django 5.1.6 on 2025-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
