# Generated by Django 5.1.6 on 2025-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePhoto',
        ),
    ]
