# Generated by Django 5.1.7 on 2025-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('href', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
